backend:
  name: git-gateway
  branch: main
  site_domain: osservatoreteocratico.github.io/BlogOT/ # Aggiungi questa riga

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "✍️ Articoli e Studi"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Autore", name: "author", widget: "string", default: "Redazione"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Bozza", name: "draft", widget: "boolean", default: false}
      - {label: "Contenuto", name: "body", widget: "markdown"}

  - name: "commenti"
    label: "💬 Moderazione Commenti"
    folder: "data/comments"
    create: false
    fields:
      - {label: "Stato", name: "status", widget: "select", options: ["In Attesa", "Approvato", "Spam"]}
      - {label: "Messaggio", name: "body", widget: "text"}
